### ISSUE TITLE
Dancer2::Plugin::JWT doesn't work with multiple apps

### ISSUE THREAD

**Issue by clemep-sios** [ambs/Dancer2-Plugin-JWT#10]
Following test app displays the problem:

```
use Test::More;
use Plack::Test;
use HTTP::Request::Common;
use Ref::Util qw<is_coderef>;

package AppA {
        use Dancer2;
        use Dancer2::Plugin::JWT;

        hook before_request => \&Util::before_request;

        get '/' => sub {
                return;
        };
};

package AppB {
        use Dancer2;
        use Dancer2::Plugin::JWT;

        hook before_request => \&Util::before_request;

        get '/' => sub {
                return;
        };
};

package Util {
        # use Dancer2;
        use Dancer2::Plugin::JWT;

        sub before_request {
                my $app = shift;
                my $jwt = jwt;

                print "BEFORE REQUEST WORKED: " . $app->name . " " . $jwt . "\n";
        }
};

my $a = AppA->to_app;
ok(is_coderef($a), 'Got AppA');

my $b = AppB->to_app;
ok(is_coderef($b), 'Got AppB');

my $t1 = Plack::Test->create($a);

my $r1 = $t1->request(GET '/');
is($r1->code, 200, 'GET / A');

my $t2 = Plack::Test->create($b);

my $r2 = $t2->request(GET '/');
is($r2->code, 200, 'GET / B');

done_testing();
```

as-is, the above takes `jwt` as a bareword (I cannot `use strict` or I get complaints) and it ends up rendered as just a string "jwt":
```
BEFORE REQUEST WORKED: AppA jwt
```
So it seems that `jwt` never gets properly registered.

If I uncomment the `# use Dancer2;` in package Util, then I get a stack trace due to:
```
Thu Dec 24 15:40:27 2020 error: AppA Route exception: Exception caught in 'core.app.before_request' filter: Hook error: Can't call method "var" on an undefined value at /root/perl5/lib/perl5/Dancer2/Plugin/JWT.pm line 32.
```
The `use Dancer2` in Util makes `jwt` reference the "Util" app that gets auto-created and causes the `app->request` (which `var` is a member of) to be undefined, rather than a pointer to `AppA` or `AppB` request.

Any way to make this work?

**Comment by ambs** [comment]
As any other Dancer2 specific DSL command, `jwt`  just works if you have Dancer2 loaded, and is used inside a route.
Therefore, you can't use it in a function in your own module. You should pass its value, calling `jwt` in the original Dancer app, or you should try to find out how to call a DSL command from the `$app` reference (that should be possible, not sure how).

**Comment by clemep-sios** [comment]
OK, so `jwt` and other DSL commands cannot be used in a multi-app Dancer2 project (without duplication of a large amount of code)? That seems like a pretty big limitation of the framework.

**Comment by ambs** [comment]
I suppose that's true, but I do not develop the Dancer 2 core for a long time.
I suspect that, given you have `$app` you might be able to call `$app->jwt` or `$app->app->jwt`.
But again, not sure.

**Comment by clemep-sios** [comment]
Thanks for the suggestions, but `jwt` takes only the single implied parameter `dsl`, which the framework gives it.

JWT.pm:
```
register jwt => sub {
    my $dsl = shift;
```

So calling as `$app->jwt` just fails. So there does not appear to be a way to make this work.

**Comment by ambs** [comment]
Didn't test, but someone in the #dancer IRC channel suggested:
```
$app->get_plugin('Dancer2::Plugin::JWT')->jwt
```

can you test?

**Comment by clemep-sios** [comment]
That doesn't work:

`Exception caught in 'core.app.before_request' filter: Hook error: Can't locate object method "get_plugin" via package "Dancer2::Core::App"`



Testing is as simple as pasting that line into the original test program I included in the bug report, if you want to test.

**Comment by ambs** [comment]
Pasting your code, I get
```
 ambs  ⎇  master  ~/tmp   perl foo.pl
ok 1 - Got AppA
ok 2 - Got AppB
BEFORE REQUEST WORKED: AppA jwt
ok 3 - GET / A
BEFORE REQUEST WORKED: AppB jwt
ok 4 - GET / B
1..4
````

**Comment by clemep-sios** [comment]
Right, like I said, you have to uncomment the `use Dancer2` in Util. Then you'll see the error. As-is `jwt` is treated as a bareword (i.e., literal string "jwt").

**Comment by ambs** [comment]
My previous post was almost correct: `my $jwt = $app->with_plugin("Dancer2::Plugin::JWT")->jwt;`

**Comment by clemep-sios** [comment]
Ah, thanks. That does seem to work. I'll close the issue.

**Comment by ambs** [comment]
Great. Sorry for not helping faster, but I needed to dig stuff I never used.
