### ISSUE TITLE
Optionally not use cookie and not send back Authorization header

### ISSUE THREAD

**Issue by mikkoi** [ambs/Dancer2-Plugin-JWT#11]
I am using [Dancer2::Plugin::JWT](https://metacpan.org/pod/Dancer2::Plugin::JWT)  in a REST API and I do not want the API to send back any extra fields. By default Dancer2::Plugin::JWT sets both a cookie and the Authorization header. Cookie becomes header 'Set-Cookie' in the HTTP response message. In my REST API, JWT is only used in the HTTP request message. It is not returned.

Can we make these optional?

**Comment by ambs** [comment]
Dear Mikko
Thank you for using Dancer2::Plugin::JWT.

At the moment we do not have any mechanism to skip the cookie. 
Also, unfortunately, I've been overwhelmed with work, and do not have a near slot to look into this issue.
If you could go through the code (it is a small module) and propose a pull request, I would be happy to review, merge it and release a new version.

Sorry for not being able to do more for you at this specific moment.

**Comment by mikkoi** [comment]
Hi @ambs,

I have created a pull request to fix the issue. Please review it.
I added new test cases to verify it works.
I have not changed - AFAIK - the default functionality.

**Comment by ambs** [comment]
Dear @mikkoi,
Thank you. I will review it and release the module. If not before, during the next weekend.
