### ISSUE TITLE
Cookies are still checked, even if set_cookie_header is disabled

### ISSUE THREAD

**Issue by sdt** [ambs/Dancer2-Plugin-JWT#20]
Hello,

I hit an issue recently where I'd changed my app to use `set_cookie_header => 0`, as I only wanted to be using the auth headers.

Because I'd already been running with the cookies, browsers still had that cookie, but now with a stale jwt. The before hook still checks for the cookie, and it clobbers any jwt found in the auth headers.

Some users worked just fine, others were getting strange immediate session expiry problems. Turns out those users still had the cookie with a now-stale jwt.

Changing the before hook to only check the cookie if $set_cookie_header is true seems to fix things.

**Comment by ambs** [comment]
Hello, @sdt. Are you able to prepare a PR? That would make it easier for me to have a quick new release. 
Thank you!

**Comment by sdt** [comment]
Hi @ambs. I've made a quick pull request #21.

I'd like to create a test for this, but I'm not sure whether this fix is generally applicable, or only suitable for my use-case. That, and I'm a little under the hammer at $work right now.

**Comment by ambs** [comment]
No problem. Merged and released.
Thanks

**Comment by sdt** [comment]
Thank you!
