### ISSUE TITLE
'Can't locate object method "push_header" via package "Dancer2::Core::Response::Delayed"

### ISSUE THREAD

**Issue by starlilyth** [ambs/Dancer2-Plugin-JWT#8]
Not sure why this error is happening, any assistance is appreciated. 

$Dancer2::Plugin::JWT::VERSION = '0.016';
$Dancer2::Core::Response::Delayed::VERSION = '0.207000';

main::__ANON__('Can\'t locate object method "push_header" via package "Dancer2::Core::Response::Delayed" at /usr/local/share/perl5/Dancer2/Plugin/JWT.pm line 165.^J') called at /usr/local/share/perl5/Dancer2/Plugin/JWT.pm line 165
Dancer2::Plugin::JWT::__ANON__('Dancer2::Core::Response::Delayed=HASH(0x40c61b0)') called at /usr/local/share/perl5/Dancer2/Core/Hook.pm line 33
eval {...} at /usr/local/share/perl5/Dancer2/Core/Hook.pm line 33
Dancer2::Core::Hook::__ANON__('Dancer2::Core::Response::Delayed=HASH(0x40c61b0)') called at /usr/local/share/perl5/Dancer2/Plugin.pm line 597
Dancer2::Plugin::__ANON__('Dancer2::Core::Response::Delayed=HASH(0x40c61b0)') called at /usr/local/share/perl5/Dancer2/Core/App.pm line 36
Dancer2::Core::App::__ANON__('CODE(0x69a9778)', 'Dancer2::Core::Response::Delayed=HASH(0x40c61b0)') called at /usr/local/share/perl5/Dancer2/Core/App.pm line 1186
eval {...} at /usr/local/share/perl5/Dancer2/Core/App.pm line 1187
Dancer2::Core::App::__ANON__('Dancer2::Core::Response::Delayed=HASH(0x40c61b0)') called at /usr/local/share/perl5/Dancer2/Core/Role/Hookable.pm line 115
Dancer2::Core::Role::Hookable::execute_hook('Dancer2::Core::App=HASH(0x3b82c20)', 'core.app.after_request', 'Dancer2::Core::Response::Delayed=HASH(0x40c61b0)') called at /usr/local/share/perl5/Dancer2/Core/App.pm line 685
Dancer2::Core::App::__ANON__('CODE(0x3ab7ff0)', 'Dancer2::Core::App=HASH(0x3b82c20)', 'core.app.after_request', 'Dancer2::Core::Response::Delayed=HASH(0x40c61b0)') called at (eval 440) line 1
Dancer2::Core::App::__ANON__('Dancer2::Core::App=HASH(0x3b82c20)', 'core.app.after_request', 'Dancer2::Core::Response::Delayed=HASH(0x40c61b0)') called at (eval 442) line 2
Dancer2::Core::App::execute_hook('Dancer2::Core::App=HASH(0x3b82c20)', 'core.app.after_request', 'Dancer2::Core::Response::Delayed=HASH(0x40c61b0)') called at /usr/local/share/perl5/Dancer2/Core/App.pm line 1540
Dancer2::Core::App::dispatch('Dancer2::Core::App=HASH(0x3b82c20)', 'HASH(0x20f9030)') called at /usr/local/share/perl5/Dancer2/Core/App.pm line 1395
Dancer2::Core::App::__ANON__ at /usr/local/share/perl5/Dancer2/Core/App.pm line 36
Dancer2::Core::App::__ANON__('CODE(0x6e16c30)') called at /usr/local/share/perl5/Dancer2/Core/App.pm line 1395

**Comment by starlilyth** [comment]
Thanks to pink_mist in Freenode/#perl for the following fix: 
On lines 164 and 236, before the '$response->push_header' lines, insert the following: 
`$response = $response->isa('Dancer2::Core::Response') ? $response : $response->response;`

**Comment by ambs** [comment]
Thank you for the note. Will try to fix and release asap

**Comment by ambs** [comment]
I wonder why is this happening. Got no issues on my end. But applying patch anyway.

**Comment by ambs** [comment]
0.017 in its way to cpan. Thanks.
